[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "n8n start"
healthcheckPath = "/healthz"
healthcheckTimeout = 25
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

